# Generated by Django 4.2.3 on 2023-07-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Xiaomi', 'Xiaomi'), ('Huawei', 'Huawei'), ('Motorola', 'Motorola'), ('OnePlus', 'OnePlus')], max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estoque', models.PositiveIntegerField()),
            ],
        ),
    ]
