# Generated by Django 4.2.3 on 2023-07-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celular',
            name='foto',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
